### ISSUE TITLE
Lizenz MIT oder GPLv2?

### ISSUE THREAD

**Issue by ThomasLeister** [campino2k/Einkaufsliste#11]
Hi,

hab gerade gesehen, dass in der bower.js von der MIT Lizenz die Rede ist, aber in der Readme wird die GPLv2 als Lizenz genannt. Welche gilt? ;)

**Comment by campino2k** [comment]
Hallo Thomas,
danke für den Hinweis. Die MIT ist beim Erstellen der bower.json so durchgerutscht. Die GPLv2 ist die Lizenz des Projektes
