### ISSUE TITLE
nginx?

### ISSUE THREAD

**Issue by johnnydvc** [campino2k/Einkaufsliste#14]
Hey,
gibt es die Möglichkeit die Einkaufsliste auch auf einem nginx Server zu betreiben?
Gruß

**Comment by chrisjung-dev** [comment]
Hi. Klar gibt es das. Dazu musst Du die .htaccess-Datei vermutlich ein bisschen für nginx anpassen, z.B. mit diesem Tool hier: http://www.winginx.com/en/htaccess

bzw. du kannst hier schauen: http://help.slimframework.com/discussions/problems/993-nginx-slim-in-sub-directory

Ausschlagebend ist hier vermutlich, dass die db-api im Verzeichnis db/ liegt.
