### ISSUE TITLE
bower =?

### ISSUE THREAD

**Issue by ParoTheParrot** [campino2k/Einkaufsliste#7]
Hallo! Was ist bower? Und wie kann ich die EInkaufsliste zum Laufen bekommen - ohne dieses bower?
Einfach alles auf meinen Webserver kopieren geht nicht (leere Seite, bis auf die Fußzeile)

**Comment by campino2k** [comment]
Hi ParoTheParrot,

ich habe das finale Projekt mit den zusätzlichen Libraries mal unter dem Tag hochgeladen:

https://github.com/campino2k/Einkaufsliste/releases/tag/0.7.0.

**Comment by ParoTheParrot** [comment]
Ja, fein! Geht jetzt!
Eine andere frage. "Anzahl" ist streng ein Zahl. So etwas wie "200g" oder "3 Liter" kann man nicht eingetragen. Finde ich etwas ungünstig. Warum wird hier konsequent eine Zahl erwartet?

**Comment by campino2k** [comment]
weil das die Erfassung von Zahlen einfacher macht, indem auf dem Handy (dafür ist die Liste ausgelegt) eine Zahlentastatur angezeigt wird. Eine Abstraktion auf Liter oder andere Einheiten müsste man ggf. in der Beschreibung machen. Wobei "Hackfleisch (200)" und "Milch (3)" recht eindeutig sind.

Ein zusätzliches Feld für Einheiten erwäge ich eigentlich nicht, das macht das Interface wieder unübersichtlicher.
